name: Node.js CI

on:
  push:
    branches:
     - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node_version: '10.X'
    - run: npm ci
    - run: npm run lint
